### ISSUE TITLE
AttributeError: module 'tensorpack.dataflow.dataset' has no attribute 'AVA2012'

### ISSUE THREAD

**Issue by PRAYALANKAR** [Openning07/MPADA#2]
AttributeError: module 'tensorpack.dataflow.dataset' has no attribute 'AVA2012'

**Comment by Openning07** [comment]
I give my implementation, i.e., MPADA/blob/master/AVA_info/ava2012.py, which I used through my experiments on AVA dataset. Some necessary files, e.g., the training file list and the test file list, can be found in MPADA/tree/master/AVA_info.

**Comment by Openning07** [comment]
And of course, due to the different environment (e.g., the version of CUDA or cv2), you need to change some code lines to make it work in your environment.

**Comment by cherryolg** [comment]
Hello, have you solved your problem? I have the same problem. What does that mean? "You need to put the ava2012. Py in AVA_info in the folder of tensorpack. dataflow. dataset." can give me more details on that？
