### ISSUE TITLE
AssertionError: *** The txt file of image list (/home/luofan1/tensorpack_data/AVA2012/val.txt) to load does not exist

### ISSUE THREAD

**Issue by luofan18** [Openning07/MPADA#3]
Could you mind sharing you val.txt and train.txt file? Are these two files created with AVA_info/AVA_test.lst, AVA_info/AVA_train.lst and AVA_info/AVA_scores.txt?

**Comment by Openning07** [comment]
They are in the **AVA_info**: https://github.com/Openning07/MPADA/tree/master/AVA_info.
