### ISSUE TITLE
Is it possible to provide a predict.py script for custom images

### ISSUE THREAD

**Issue by idiomer** [Openning07/MPADA#6]
This model looks very exciting. So I want to apply it to my  dataset. Is it possible to provide a script to predict scores of  
 given images that from a folder. Thank you so much

**Comment by Openning07** [comment]
Sure. You can use [`--eval`](https://github.com/Openning07/MPADA/blob/master/AVA2012-resnet_20180808_Revised.py#L246) and turn into evaluation mode.
